#!/usr/bin/with-contenv bash

# DEFAULT_CONFIG is set in container's env
DEFAULT_CONFIG="${DEFAULT_CONFIG:?Expected DEFAULT_CONFIG env var to be set and not empty}"
CONFIG=/config/qBittorrent

set -e

# Copy over the new config while backing up any overwrites
backup_dir="/config/backup-$(date +%FT%T)"
rsync -vv --checksum -a --backup --backup-dir="${backup_dir}/" "${DEFAULT_CONFIG}/" "${CONFIG}/"
