[BitTorrent]
Session\Port=${LISTENING_PORT}
Session\Preallocation=true

; Seeding
Session\GlobalMaxRatio=2
Session\GlobalMaxSeedingMinutes=10080
Session\GlobalMaxInactiveSeedingMinutes=10080

; Do not change to manual mode, relocate torrents when paths or categories change
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false

; Paths and layout
Session\SubcategoriesEnabled=true
Session\TorrentContentLayout=Subfolder
Session\TempPathEnabled=true
Session\TempPath=${TORRENT_ROOT}/Torrents/temp/
Session\DefaultSavePath=${TORRENT_ROOT}/Torrents/
Session\FinishedTorrentExportDirectory=${TORRENT_ROOT}/_torrents/Completed/

; Queuing
Session\AddTorrentPaused=true
Session\QueueingSystemEnabled=true
; default values
Session\MaxActiveTorrents=50
Session\MaxActiveDownloads=25
Session\MaxActiveUploads=25
; ignore slow torrents as defined below from queue limits
Session\IgnoreSlowTorrentsForQueueing=true
; in KiB/s
Session\SlowTorrentsDownloadRate=2
Session\SlowTorrentsUploadRate=2
; in seconds
Session\SlowTorrentsInactivityTimer=60

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Network]
PortForwardingEnabled=true

[Preferences]
Advanced\RecheckOnCompletion=true
General\Locale=en

; Web UI
WebUI\Enabled=true
WebUI\Address=*
WebUI\ServerDomains=*
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=192.168.1.1/22
WebUI\Username=hashhar
WebUI\Password_PBKDF2="@ByteArray(9x2A6Dp+RQIu7vHa5xGbOQ==:bLaWmprpPVijOICXKOiFO0TnNPD52FEbXklBZTCbNqpafqIqnM9ROr/QJuZg5SHWGTFmAJYxzgQ9u0lzDnuipQ==)"
WebUI\UseUPnP=true

; Connection
Connection\PortRangeMin=${LISTENING_PORT}
Connection\UPnP=true
