version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/alertmanager"
      - "/caddy"
      - "/gallery-dl"
      - "/prometheus"
      - "/qbittorrent"
      - "/restic-rest-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/immich"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hashhar/*"
      - dependency-name: "ghcr.io/immich-app/postgres"
